"use client";

import { useState, useEffect } from "react";
import Image from "next/image";
import Link from "next/link";
import { useTheme, getStyleSettings, StyleType } from "../ThemeContext";
import { useBackground } from "../context/BackgroundContext";
import Header from "../components/Header";
import Footer from "../components/Footer";

type FeatureId = "memory" | "inventory" | "companionInventory" | "companion" | "minimap" | "environments" | "save" | "genre" | "gamemaster" | "voice" | "soundfx";

export default function Features() {
  const { currentStyle, setCurrentStyle } = useTheme();
  const { getPageBackground } = useBackground();
  const currentSettings = getStyleSettings(currentStyle);

  // Get the background image for this page
  const pageBackground = getPageBackground('features');

  // Features data
  const features = [
    {
      id: "environments" as FeatureId,
      title: "Generated Environments",
      description: "Each location is dynamically created through prompt engineering and AI image generation, allowing for infinitely varied settings that evolve based on the narrative context."
    },
    {
      id: "minimap" as FeatureId,
      title: "Self-Generated Minimap",
      description: "Explore the world with a dynamically generated minimap that tracks your journey and reveals new locations as you discover them, giving you a visual record of your adventure."
    },
    {
      id: "voice" as FeatureId,
      title: "Voice Generation",
      description: "Experience immersive storytelling with unique AI-generated voices for each character. Our advanced voice synthesis creates distinctive, emotionally expressive speech that brings your companions and NPCs to life."
    },
    {
      id: "soundfx" as FeatureId,
      title: "Sound Effect Generation",
      description: "Enhance your adventure with dynamically generated sound effects that respond to your environment and actions. From magical spells to futuristic technology, every interaction is accompanied by contextually appropriate audio."
    },
    {
      id: "companion" as FeatureId,
      title: "Companion System",
      description: "Build a party of companions with unique personalities, portraits, and voices—all generated by our AI. Each companion has their own stats, inventory, and relationships that evolve throughout your journey."
    },
    {
      id: "companionInventory" as FeatureId,
      title: "Companion Inventory",
      description: "Each companion carries their own inventory with unique items, equipment, and resources that can be shared, traded, or strategically distributed among your team members."
    },
    {
      id: "inventory" as FeatureId,
      title: "Dynamic Inventory System",
      description: "Collect and manage items with AI-generated sprites created on-the-fly. The AI can add, remove, and transform items in your inventory based on your actions and the narrative context."
    },
    {
      id: "gamemaster" as FeatureId,
      title: "AI Game Master",
      description: "Our system features an intelligent AI Game Master that manages the game world, character interactions, and narrative flow, creating a dynamic and responsive storytelling experience tailored to your choices."
    },
    {
      id: "genre" as FeatureId,
      title: "Ask for Your World",
      description: "Ask for any world you can imagine—Fantasy, Anime, Realistic, Sci-Fi, or something entirely unique—and watch your novel transform visually and narratively to bring your vision to life."
    },
    {
      id: "save" as FeatureId,
      title: "Save and Load System",
      description: "Our innovative save system allows you to save your progress at any point and return to continue your adventure exactly where you left off, with all character relationships and world states preserved."
    },
    {
      id: "memory" as FeatureId,
      title: "Persistent Memory",
      description: "Our system allows you to embark on as many adventures as you desire, with every story stored securely on your device. Each journey remembers your choices, progress, and key moments, enabling a seamless continuation whenever you return."
    }
  ];

  return (
    <main className="relative min-h-screen flex flex-col overflow-hidden">
      {/* Background */}
      <div className="absolute inset-0 z-0">
        <div 
          className="absolute inset-0 bg-cover bg-center transition-all duration-1000 ease-in-out"
          style={{ backgroundImage: `url(${pageBackground.desktop})` }}
        />
        <div className="absolute inset-0 bg-black/30" />
        <div className={`absolute inset-0 bg-gradient-to-b ${currentSettings.themeColor} opacity-25`} />
      </div>

      {/* Header */}
      <Header />

      {/* Content */}
      <section className="relative z-10 flex flex-col items-center justify-center flex-1 px-4 py-8 pt-28 md:pt-32">
        <h1 className={`text-4xl font-bold mb-4 text-white drop-shadow-lg ${currentSettings.subtitleFont}`}>{currentSettings.title}</h1>
        
        <div className="max-w-6xl mx-auto">
          {/* Introduction */}
          <div className="bg-black/30 backdrop-blur-sm rounded-lg p-6 mb-8 text-center">
            <h2 className={`text-2xl font-bold text-white mb-4 ${currentSettings.subtitleFont}`}>
              Experience the Future of Storytelling
            </h2>
            <p className="text-white/90 max-w-3xl mx-auto">
              Endless Novel combines advanced AI with thoughtful narrative design to create stories that feel alive. 
              Discover how our technology transforms passive reading into an interactive journey where your 
              choices shape a truly personalized narrative experience.
            </p>
          </div>
          
          {/* Features Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-8">
            {features.map((feature, index) => (
              <div 
                key={index} 
                className={`${currentSettings.featureCardBg} backdrop-blur-sm rounded-lg p-6 transition-all duration-300 hover:transform hover:scale-[1.02] hover:shadow-lg`}
              >
                <div className="w-full h-40 rounded-lg overflow-hidden mb-4">
                  <Image 
                    src={currentSettings.featureImages[feature.id]} 
                    alt={feature.title}
                    width={400}
                    height={225}
                    className="w-full h-full object-cover"
                  />
                </div>
                <h3 className={`text-xl font-bold mb-2 ${currentSettings.featureHighlight}`}>{feature.title}</h3>
                <p className="text-white/80">{feature.description}</p>
              </div>
            ))}
          </div>
          
          {/* Technology Section */}
          <div className="bg-black/30 backdrop-blur-sm rounded-lg p-6 mb-8">
            <h2 className={`text-2xl font-bold text-white mb-4 ${currentSettings.subtitleFont}`}>Our Technology</h2>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
              <div>
                <h3 className={`text-xl font-bold mb-3 ${currentSettings.featureHighlight}`}>AI-API Architecture</h3>
                <p className="text-white/90 mb-4">
                  Endless Novel harnesses the power of multiple AI APIs through sophisticated prompt engineering and a custom
                  Python orchestration layer. Rather than traditional game engines, we've built a system that coordinates
                  various AI models to create a cohesive, dynamic experience.
                </p>
                <ul className="space-y-2 text-white/80">
                  <li className="flex items-start">
                    <span className={`mr-2 ${currentSettings.featureHighlight}`}>✓</span> 
                    <span>Claude 3.7 and Gemini for core narrative generation and character interactions</span>
                  </li>
                  <li className="flex items-start">
                    <span className={`mr-2 ${currentSettings.featureHighlight}`}>✓</span> 
                    <span>On-the-fly generation of character portraits, item sprites, and environment visuals</span>
                  </li>
                  <li className="flex items-start">
                    <span className={`mr-2 ${currentSettings.featureHighlight}`}>✓</span> 
                    <span>AI-driven voice synthesis for unique character voices and narration</span>
                  </li>
                  <li className="flex items-start">
                    <span className={`mr-2 ${currentSettings.featureHighlight}`}>✓</span> 
                    <span>Custom prompt engineering for consistent world-building and character development</span>
                  </li>
                </ul>
              </div>
              <div className="rounded-lg overflow-hidden shadow-xl">
                <Image 
                  src={`/images/technology/${currentStyle}.jpg`}
                  alt="AI Technology" 
                  width={600}
                  height={400}
                  className="w-full h-auto object-cover"
                />
              </div>
            </div>
          </div>
          
          {/* Gameplay Mechanics Section */}
          <div className="bg-black/30 backdrop-blur-sm rounded-lg p-6 mb-8">
            <h2 className={`text-2xl font-bold text-white mb-6 ${currentSettings.subtitleFont}`}>Gameplay Mechanics</h2>
            
            {/* Character Development and World Interaction - REWORKED */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
              {/* Character Development */}
              <div className="bg-black/20 rounded-lg overflow-hidden transition-all duration-300 hover:transform hover:scale-[1.02] hover:shadow-lg">
                <div className="relative h-48 overflow-hidden">
                  <Image 
                    src={`/images/sections/gameplay/${currentStyle}/character_development.jpg`}
                    alt="Character Development"
                    fill
                    className="object-cover"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent flex items-end">
                    <h3 className={`text-xl font-bold p-4 ${currentSettings.featureHighlight}`}>Character Development</h3>
                  </div>
                </div>
                <div className="p-5">
                  <p className="text-white/90 mb-3">
                    Your character and companions evolve with dynamic stats, skills, and relationships that respond to your choices.
                  </p>
                  <div className="grid grid-cols-2 gap-3">
                    <div className="flex items-center">
                      <div className={`flex-shrink-0 w-8 h-8 rounded-full ${currentSettings.buttonColor} bg-opacity-20 flex items-center justify-center mr-2`}>
                        <svg className="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                        </svg>
                      </div>
                      <span className="text-white/80 text-sm">AI-generated portraits</span>
                    </div>
                    <div className="flex items-center">
                      <div className={`flex-shrink-0 w-8 h-8 rounded-full ${currentSettings.buttonColor} bg-opacity-20 flex items-center justify-center mr-2`}>
                        <svg className="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z"></path>
                        </svg>
                      </div>
                      <span className="text-white/80 text-sm">Unique voices</span>
                    </div>
                    <div className="flex items-center">
                      <div className={`flex-shrink-0 w-8 h-8 rounded-full ${currentSettings.buttonColor} bg-opacity-20 flex items-center justify-center mr-2`}>
                        <svg className="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4"></path>
                        </svg>
                      </div>
                      <span className="text-white/80 text-sm">Custom abilities</span>
                    </div>
                    <div className="flex items-center">
                      <div className={`flex-shrink-0 w-8 h-8 rounded-full ${currentSettings.buttonColor} bg-opacity-20 flex items-center justify-center mr-2`}>
                        <svg className="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"></path>
                        </svg>
                      </div>
                      <span className="text-white/80 text-sm">Persistent memory</span>
                    </div>
                  </div>
                </div>
              </div>
              
              {/* World Interaction */}
              <div className="bg-black/20 rounded-lg overflow-hidden transition-all duration-300 hover:transform hover:scale-[1.02] hover:shadow-lg">
                <div className="relative h-48 overflow-hidden">
                  <Image 
                    src={`/images/sections/gameplay/${currentStyle}/world_interaction.jpg`}
                    alt="World Interaction"
                    fill
                    className="object-cover"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent flex items-end">
                    <h3 className={`text-xl font-bold p-4 ${currentSettings.featureHighlight}`}>World Interaction</h3>
                  </div>
                </div>
                <div className="p-5">
                  <p className="text-white/90 mb-3">
                    Interact with a fully responsive environment where items, locations, and world states persist throughout your adventure.
                  </p>
                  <div className="grid grid-cols-2 gap-3">
                    <div className="flex items-center">
                      <div className={`flex-shrink-0 w-8 h-8 rounded-full ${currentSettings.buttonColor} bg-opacity-20 flex items-center justify-center mr-2`}>
                        <svg className="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z"></path>
                        </svg>
                      </div>
                      <span className="text-white/80 text-sm">Inventory system</span>
                    </div>
                    <div className="flex items-center">
                      <div className={`flex-shrink-0 w-8 h-8 rounded-full ${currentSettings.buttonColor} bg-opacity-20 flex items-center justify-center mr-2`}>
                        <svg className="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7"></path>
                        </svg>
                      </div>
                      <span className="text-white/80 text-sm">Generated maps</span>
                    </div>
                    <div className="flex items-center">
                      <div className={`flex-shrink-0 w-8 h-8 rounded-full ${currentSettings.buttonColor} bg-opacity-20 flex items-center justify-center mr-2`}>
                        <svg className="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path>
                        </svg>
                      </div>
                      <span className="text-white/80 text-sm">Environment effects</span>
                    </div>
                    <div className="flex items-center">
                      <div className={`flex-shrink-0 w-8 h-8 rounded-full ${currentSettings.buttonColor} bg-opacity-20 flex items-center justify-center mr-2`}>
                        <svg className="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M7 20l4-16m2 16l4-16M6 9h14M4 15h14"></path>
                        </svg>
                      </div>
                      <span className="text-white/80 text-sm">Dynamic world states</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            
            {/* Companion System - REWORKED */}
            <div className="mb-8">
              <div className="bg-black/20 rounded-lg overflow-hidden transition-all duration-300 hover:shadow-lg mb-6">
                <div className="relative h-60 overflow-hidden">
                  <Image 
                    src={`/images/sections/gameplay/${currentStyle}/companion_system.jpg`}
                    alt="Companion System"
                    fill
                    className="object-cover"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent flex items-end">
                    <div className="p-6">
                      <h3 className={`text-xl font-bold mb-2 ${currentSettings.featureHighlight}`}>Companion System</h3>
                      <p className="text-white/90">
                        Journey with unique companions who offer distinct personalities, abilities, and storylines that evolve based on your choices.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                {/* Companion Features */}
                <div className="bg-black/20 rounded-lg overflow-hidden transition-all duration-300 hover:transform hover:scale-[1.02] hover:shadow-lg">
                  <div className="p-5">
                    <div className="flex items-center mb-3">
                      <div className={`flex-shrink-0 w-10 h-10 rounded-full ${currentSettings.buttonColor} bg-opacity-30 flex items-center justify-center mr-3`}>
                        <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path>
                        </svg>
                      </div>
                      <h4 className="text-white font-semibold">Companion Features</h4>
                    </div>
                  <ul className="space-y-2 text-white/80">
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                        <span>Dynamic inventories and equipment</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                        <span>Unique skills and abilities</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                        <span>Customizable progression</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                        <span>Rich backstories with quests</span>
                    </li>
                  </ul>
                </div>
              </div>
              
                {/* Team Interaction */}
                <div className="bg-black/20 rounded-lg overflow-hidden transition-all duration-300 hover:transform hover:scale-[1.02] hover:shadow-lg">
                  <div className="p-5">
                    <div className="flex items-center mb-3">
                      <div className={`flex-shrink-0 w-10 h-10 rounded-full ${currentSettings.buttonColor} bg-opacity-30 flex items-center justify-center mr-3`}>
                        <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z"></path>
                        </svg>
                      </div>
                      <h4 className="text-white font-semibold">Team Interaction</h4>
                    </div>
                  <ul className="space-y-2 text-white/80">
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                        <span>Build bonds through shared experiences</span>
                      </li>
                      <li className="flex items-start">
                        <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                        <span>AI-driven behavior changes</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                        <span>Manage rivalries and conflicts</span>
                      </li>
                    </ul>
                  </div>
                </div>
                
                {/* Strategic Party Management */}
                <div className="bg-black/20 rounded-lg overflow-hidden transition-all duration-300 hover:transform hover:scale-[1.02] hover:shadow-lg">
                  <div className="p-5">
                    <div className="flex items-center mb-3">
                      <div className={`flex-shrink-0 w-10 h-10 rounded-full ${currentSettings.buttonColor} bg-opacity-30 flex items-center justify-center mr-3`}>
                        <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"></path>
                        </svg>
                      </div>
                      <h4 className="text-white font-semibold">Strategic Management</h4>
                    </div>
                    <ul className="space-y-2 text-white/80">
                      <li className="flex items-start">
                        <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                        <span>Tactical combat command</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                        <span>Strategic formations</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                        <span>Risk and reward balancing</span>
                    </li>
                  </ul>
                  </div>
                </div>
              </div>
            </div>
            
            {/* Complex Relationship Dynamics */}
            <div className="mt-8 mb-6">
              <div className="bg-black/20 rounded-lg overflow-hidden">
                <div className="grid grid-cols-1 lg:grid-cols-4 gap-0">
                  <div className="lg:col-span-1 relative">
                    <div className="h-full lg:h-auto">
                      <Image 
                        src={`/images/sections/gameplay/${currentStyle}/relationship_dynamics.jpg`}
                        alt="Complex Relationships"
                        fill
                        className="object-cover h-full w-full"
                        style={{ objectPosition: 'center' }}
                      />
                      <div className="absolute inset-0 bg-black/40 lg:hidden"></div>
                    </div>
                  </div>
                  <div className="p-6 lg:col-span-3">
                    <h3 className={`text-xl font-bold mb-4 ${currentSettings.featureHighlight}`}>Complex Relationship Dynamics</h3>
                    <p className="text-white/90 mb-4">
                      Go beyond simple allies and adversaries with deep, nuanced relationships that have real consequences.
                    </p>
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-4">
                      <div className="bg-black/30 rounded-lg p-4">
                        <h4 className={`text-lg font-semibold mb-2 ${currentSettings.featureHighlight}`}>Romance & Rivalry</h4>
                        <ul className="space-y-2 text-white/80 text-sm">
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                            <span>Fall in love with companions</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                            <span>Develop rivalries and conflicts</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                            <span>Navigate complex relationships</span>
                    </li>
                  </ul>
                </div>
                
                      <div className="bg-black/30 rounded-lg p-4">
                        <h4 className={`text-lg font-semibold mb-2 ${currentSettings.featureHighlight}`}>Life & Death</h4>
                        <ul className="space-y-2 text-white/80 text-sm">
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                            <span>Permanent death possibilities</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                            <span>Execute or sacrifice companions</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                            <span>Memorial quests for fallen allies</span>
                    </li>
                  </ul>
                </div>
                
                      <div className="bg-black/30 rounded-lg p-4">
                        <h4 className={`text-lg font-semibold mb-2 ${currentSettings.featureHighlight}`}>Loyalty & Betrayal</h4>
                        <ul className="space-y-2 text-white/80 text-sm">
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                            <span>Companions may abandon you</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                            <span>Uncover secret agendas</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                            <span>Earn back lost trust</span>
                    </li>
                  </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          
          {/* Unique Stories and Platform Availability Section */}
          <div className="bg-black/30 backdrop-blur-sm rounded-lg p-6 mb-8">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              {/* Every Story is Unique */}
              <div>
                <h3 className={`text-2xl font-bold mb-4 ${currentSettings.featureHighlight}`}>Every Story is Unique</h3>
                <p className="text-white/90 mb-6">
                  Unlike traditional books or games with predetermined paths, Endless Novel creates a truly personal narrative experience. Each playthrough leverages the generative capabilities of modern AI models to create scenarios, challenges, and character interactions that adapt to your decisions.
                </p>
                <div className="border-l-4 border-amber-500 pl-4">
                  <p className="text-white/80 italic">
                    "No two journeys through an Endless Novel will ever be the same, because the system dynamically responds to your choices with the full creative power of cutting-edge AI."
                  </p>
                </div>
              </div>
              
              {/* Platform Availability */}
              <div>
                <h3 className={`text-2xl font-bold mb-4 ${currentSettings.featureHighlight}`}>Platform Availability</h3>
                <p className="text-white/90 mb-6">
                  Endless Novel is designed for immersive experiences on larger screens. Access your adventures through our browser application, standalone desktop client, or via our Steam release.
                </p>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-6">
                  <div className="flex flex-col items-center">
                    <div className="mb-2">
                      <Image 
                        src="/images/icons/Web_Broser.png"
                        alt="Web Browser"
                        width={75}
                        height={75}
                        className="h-16 w-16 object-contain"
                      />
                    </div>
                    <span className="text-white font-medium">Web Browser</span>
                  </div>
                  <div className="flex flex-col items-center">
                    <div className="mb-2">
                      <Image 
                        src="/images/icons/Desktop_App.png"
                        alt="Desktop App"
                        width={75}
                        height={75}
                        className="h-16 w-16 object-contain"
                      />
                    </div>
                    <span className="text-white font-medium">Desktop App</span>
                  </div>
                  <div className="flex flex-col items-center">
                    <div className="mb-2">
                      <Image 
                        src="/images/icons/Steam.png"
                        alt="Steam"
                        width={75}
                        height={75}
                        className="h-16 w-16 object-contain"
                      />
                    </div>
                    <span className="text-white font-medium">Steam</span>
                  </div>
                  <div className="flex flex-col items-center">
                    <div className="mb-2 relative">
                      <Image 
                        src="/images/icons/Ipad.png"
                        alt="iPad"
                        width={75}
                        height={75}
                        className="h-16 w-16 object-contain"
                      />
                    </div>
                    <span className="text-white font-medium">iPad</span>
                    <span className="text-gray-400 text-xs">(Coming Soon)</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      
      <Footer />
    </main>
  );
} 