"use client";

import { useState, useEffect } from "react";
import Image from "next/image";
import Link from "next/link";
import { useTheme, getStyleSettings, StyleType } from "../ThemeContext";
import Header from "../components/Header";
import Footer from "../components/Footer";

type FeatureId = "memory" | "inventory" | "companionInventory" | "companion" | "minimap" | "environments" | "save" | "genre" | "gamemaster";

export default function Features() {
  const { currentStyle, setCurrentStyle } = useTheme();
  const currentSettings = getStyleSettings(currentStyle);

  // Features data
  const features = [
    {
      id: "memory" as FeatureId,
      title: "Persistent Memory",
      description: "Our system allows you to embark on as many adventures as you desire, with every story stored securely on your device. Each journey remembers your choices, progress, and key moments, enabling a seamless continuation whenever you return."
    },
    {
      id: "inventory" as FeatureId,
      title: "Dynamic Inventory System",
      description: "Collect and manage items with AI-generated sprites created on-the-fly. The AI can add, remove, and transform items in your inventory based on your actions and the narrative context."
    },
    {
      id: "companion" as FeatureId,
      title: "Companion System",
      description: "Build a party of companions with unique personalities, portraits, and voices—all generated by our AI. Each companion has their own stats, inventory, and relationships that evolve throughout your journey."
    },
    {
      id: "companionInventory" as FeatureId,
      title: "Companion Inventory",
      description: "Each companion carries their own inventory with unique items, equipment, and resources that can be shared, traded, or strategically distributed among your team members."
    },
    {
      id: "environments" as FeatureId,
      title: "Generated Environments",
      description: "Each location is dynamically created through prompt engineering and AI image generation, allowing for infinitely varied settings that evolve based on the narrative context."
    },
    {
      id: "minimap" as FeatureId,
      title: "Self-Generated Minimap",
      description: "Explore the world with a dynamically generated minimap that tracks your journey and reveals new locations as you discover them, giving you a visual record of your adventure."
    },
    {
      id: "save" as FeatureId,
      title: "Save and Load System",
      description: "Our innovative save system allows you to save your progress at any point and return to continue your adventure exactly where you left off, with all character relationships and world states preserved."
    },
    {
      id: "genre" as FeatureId,
      title: "Ask for Your World",
      description: "Ask for any world you can imagine—Fantasy, Anime, Realistic, Sci-Fi, or something entirely unique—and watch your novel transform visually and narratively to bring your vision to life."
    },
    {
      id: "gamemaster" as FeatureId,
      title: "AI Game Master",
      description: "Our system features an intelligent AI Game Master that manages the game world, character interactions, and narrative flow, creating a dynamic and responsive storytelling experience tailored to your choices."
    }
  ];

  return (
    <main className="relative min-h-screen flex flex-col overflow-hidden">
      {/* Background */}
      <div className="absolute inset-0 z-0">
        <div 
          className="absolute inset-0 bg-cover bg-center transition-all duration-1000 ease-in-out"
          style={{ backgroundImage: `url(${currentSettings.bgImage})` }}
        />
        <div className="absolute inset-0 bg-black/30" />
        <div className={`absolute inset-0 bg-gradient-to-b ${currentSettings.themeColor} opacity-25`} />
      </div>

      {/* Header */}
      <Header />

      {/* Content */}
      <section className="relative z-10 flex flex-col items-center justify-center flex-1 px-4 py-8 pt-28 md:pt-32">
        <h1 className={`text-4xl font-bold mb-4 text-white drop-shadow-lg ${currentSettings.subtitleFont}`}>{currentSettings.title}</h1>
        
        <div className="max-w-6xl mx-auto">
          {/* Introduction */}
          <div className="bg-black/30 backdrop-blur-sm rounded-lg p-6 mb-8 text-center">
            <h2 className={`text-2xl font-bold text-white mb-4 ${currentSettings.subtitleFont}`}>
              Experience the Future of Storytelling
            </h2>
            <p className="text-white/90 max-w-3xl mx-auto">
              Endless Novel combines advanced AI with thoughtful narrative design to create stories that feel alive. 
              Discover how our technology transforms passive reading into an interactive journey where your 
              choices shape a truly personalized narrative experience.
            </p>
          </div>
          
          {/* Features Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-8">
            {features.map((feature, index) => (
              <div 
                key={index} 
                className={`${currentSettings.featureCardBg} backdrop-blur-sm rounded-lg p-6 transition-all duration-300 hover:transform hover:scale-[1.02] hover:shadow-lg`}
              >
                <div className="w-full h-40 rounded-lg overflow-hidden mb-4">
                  <Image 
                    src={currentSettings.featureImages[feature.id]} 
                    alt={feature.title}
                    width={400}
                    height={225}
                    className="w-full h-full object-cover"
                  />
                </div>
                <h3 className={`text-xl font-bold mb-2 ${currentSettings.featureHighlight}`}>{feature.title}</h3>
                <p className="text-white/80">{feature.description}</p>
              </div>
            ))}
          </div>
          
          {/* Technology Section */}
          <div className="bg-black/30 backdrop-blur-sm rounded-lg p-6 mb-8">
            <h2 className={`text-2xl font-bold text-white mb-4 ${currentSettings.subtitleFont}`}>Our Technology</h2>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
              <div>
                <h3 className={`text-xl font-bold mb-3 ${currentSettings.featureHighlight}`}>AI-API Architecture</h3>
                <p className="text-white/90 mb-4">
                  Endless Novel harnesses the power of multiple AI APIs through sophisticated prompt engineering and a custom
                  Python orchestration layer. Rather than traditional game engines, we've built a system that coordinates
                  various AI models to create a cohesive, dynamic experience.
                </p>
                <ul className="space-y-2 text-white/80">
                  <li className="flex items-start">
                    <span className={`mr-2 ${currentSettings.featureHighlight}`}>✓</span> 
                    <span>Claude 3.7 and Gemini for core narrative generation and character interactions</span>
                  </li>
                  <li className="flex items-start">
                    <span className={`mr-2 ${currentSettings.featureHighlight}`}>✓</span> 
                    <span>On-the-fly generation of character portraits, item sprites, and environment visuals</span>
                  </li>
                  <li className="flex items-start">
                    <span className={`mr-2 ${currentSettings.featureHighlight}`}>✓</span> 
                    <span>AI-driven voice synthesis for unique character voices and narration</span>
                  </li>
                  <li className="flex items-start">
                    <span className={`mr-2 ${currentSettings.featureHighlight}`}>✓</span> 
                    <span>Custom prompt engineering for consistent world-building and character development</span>
                  </li>
                </ul>
              </div>
              <div className="rounded-lg overflow-hidden shadow-xl">
                <Image 
                  src={`/images/technology/${currentStyle}.jpg`}
                  alt="AI Technology" 
                  width={600}
                  height={400}
                  className="w-full h-auto object-cover"
                />
              </div>
            </div>
          </div>
          
          {/* Gameplay Mechanics Section */}
          <div className="bg-black/30 backdrop-blur-sm rounded-lg p-6 mb-8">
            <h2 className={`text-2xl font-bold text-white mb-6 ${currentSettings.subtitleFont}`}>Gameplay Mechanics</h2>
            
            {/* Character Development and World Interaction */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
              {/* Character Development */}
              <div className="bg-black/20 rounded-lg p-6">
                <h3 className={`text-xl font-bold mb-4 ${currentSettings.featureHighlight}`}>Character Development</h3>
                <p className="text-white/90 mb-4">
                  Your character and companions evolve throughout the adventure with dynamically tracked statistics, skills, and relationships. The AI remembers injuries, emotional states, and growth opportunities for each character in your party.
                </p>
                <div className="bg-black/20 rounded-lg p-4">
                  <h4 className="text-white font-semibold mb-2">Character Features:</h4>
                  <ul className="space-y-2 text-white/80">
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                      <span>Unique AI-generated portraits that reflect character development</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                      <span>Distinctive voices created through voice synthesis technology</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                      <span>Individual inventories, abilities, and relationship dynamics</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                      <span>Persistent memories that influence behavior and dialogue options</span>
                    </li>
                  </ul>
                </div>
              </div>
              
              {/* World Interaction */}
              <div className="bg-black/20 rounded-lg p-6">
                <h3 className={`text-xl font-bold mb-4 ${currentSettings.featureHighlight}`}>World Interaction</h3>
                <p className="text-white/90 mb-4">
                  Our system creates a fully interactive environment where items can be manipulated, locations discovered, and the state of the world persistently tracked through your adventure.
                </p>
                <div className="bg-black/20 rounded-lg p-4">
                  <h4 className="text-white font-semibold mb-2">World Features:</h4>
                  <ul className="space-y-2 text-white/80">
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                      <span>Intelligently managed inventory with item transfers between characters</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                      <span>Procedurally generated maps that expand as you explore</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                      <span>Location-aware interactions with environmental consequences</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                      <span>State-aware AI that can fundamentally alter the game world</span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            
            {/* Companion System */}
            <div className="mb-4">
              <h3 className={`text-xl font-bold mb-4 ${currentSettings.featureHighlight}`}>Companion System</h3>
              <p className="text-white/90 mb-6">
                Your journey becomes richer with a party of unique companions, each offering distinct personalities, abilities, and challenges. Build relationships, unlock their stories, and shape the outcome of your adventure through their dynamic involvement.
              </p>
              
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                {/* Companion Features */}
                <div className="bg-black/20 rounded-lg p-5">
                  <h4 className="text-white font-semibold mb-3">Companion Features:</h4>
                  <ul className="space-y-3 text-white/80">
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                      <span>Dynamic Inventories: Equip companions with tailored gear and share party resources</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                      <span>Skill Sets and Abilities: Assign specialized skills and unlock powerful abilities</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                      <span>Stat Points and Progression: Customize companions by distributing stat points</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                      <span>Alignment and Morality: Companions have unique alignments that influence their loyalty</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                      <span>Rich Backstories: Explore detailed quests tied to each companion's past</span>
                    </li>
                  </ul>
                </div>
                
                {/* Team Interaction */}
                <div className="bg-black/20 rounded-lg p-5">
                  <h4 className="text-white font-semibold mb-3">Team Interaction:</h4>
                  <p className="text-white/80 mb-3 text-sm">
                    Interact dynamically with your companions and watch them evolve based on your choices and adventures.
                  </p>
                  <ul className="space-y-3 text-white/80">
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                      <span>Relationship Dynamics: Build bonds through dialogue, decisions, and shared experiences</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                      <span>AI-Driven Behavior: Companions react to your choices with changing attitudes</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                      <span>Conflict and Loyalty: Manage rivalries and foster bonds between companions</span>
                    </li>
                  </ul>
                </div>
                
                {/* Strategic Party Management */}
                <div className="bg-black/20 rounded-lg p-5">
                  <h4 className="text-white font-semibold mb-3">Strategic Party Management:</h4>
                  <p className="text-white/80 mb-3 text-sm">
                    Strategically manage your party to overcome challenges and adapt to encounters.
                  </p>
                  <ul className="space-y-3 text-white/80">
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                      <span>Tactical Combat: Command companions in battles using their unique abilities</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                      <span>Formation and Roles: Arrange your party in formations for strategic advantage</span>
                    </li>
                    <li className="flex items-start">
                      <span className={`mr-2 ${currentSettings.featureHighlight}`}>•</span> 
                      <span>Companion Risk and Reward: Balance risks with rare opportunities to revive companions</span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          
          {/* Unique Stories and Platform Availability Section */}
          <div className="bg-black/30 backdrop-blur-sm rounded-lg p-6 mb-8">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              {/* Every Story is Unique */}
              <div>
                <h3 className={`text-2xl font-bold mb-4 ${currentSettings.featureHighlight}`}>Every Story is Unique</h3>
                <p className="text-white/90 mb-6">
                  Unlike traditional books or games with predetermined paths, Endless Novel creates a truly personal narrative experience. Each playthrough leverages the generative capabilities of modern AI models to create scenarios, challenges, and character interactions that adapt to your decisions.
                </p>
                <div className="border-l-4 border-amber-500 pl-4">
                  <p className="text-white/80 italic">
                    "No two journeys through an Endless Novel will ever be the same, because the system dynamically responds to your choices with the full creative power of cutting-edge AI."
                  </p>
                </div>
              </div>
              
              {/* Platform Availability */}
              <div>
                <h3 className={`text-2xl font-bold mb-4 ${currentSettings.featureHighlight}`}>Platform Availability</h3>
                <p className="text-white/90 mb-6">
                  Endless Novel is designed for immersive experiences on larger screens. Access your adventures through our browser application, standalone desktop client, or via our Steam release.
                </p>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-6">
                  <div className="flex flex-col items-center">
                    <div className="mb-2">
                      <Image 
                        src="/images/icons/Web_Broser.png"
                        alt="Web Browser"
                        width={75}
                        height={75}
                        className="h-16 w-16 object-contain"
                      />
                    </div>
                    <span className="text-white font-medium">Web Browser</span>
                  </div>
                  <div className="flex flex-col items-center">
                    <div className="mb-2">
                      <Image 
                        src="/images/icons/Desktop_App.png"
                        alt="Desktop App"
                        width={75}
                        height={75}
                        className="h-16 w-16 object-contain"
                      />
                    </div>
                    <span className="text-white font-medium">Desktop App</span>
                  </div>
                  <div className="flex flex-col items-center">
                    <div className="mb-2">
                      <Image 
                        src="/images/icons/Steam.png"
                        alt="Steam"
                        width={75}
                        height={75}
                        className="h-16 w-16 object-contain"
                      />
                    </div>
                    <span className="text-white font-medium">Steam</span>
                  </div>
                  <div className="flex flex-col items-center">
                    <div className="mb-2 relative">
                      <Image 
                        src="/images/icons/Ipad.png"
                        alt="iPad"
                        width={75}
                        height={75}
                        className="h-16 w-16 object-contain"
                      />
                    </div>
                    <span className="text-white font-medium">iPad</span>
                    <span className="text-gray-400 text-xs">(Coming Soon)</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      
      <Footer />
    </main>
  );
} 